theme: jekyll-theme-chirpy

baseurl: ''

lang: en

timezone: Europe/Madrid

title: ΛLΣJΛПDЯOΛLSΛ

tagline: CEO-DIWES / DevOps

description: >-
  Blog Personal de Alejandro Alfaro Sanchez. Aquí encontrarás tutoriales, guías y cursos para mejorar tus habilidades en programación, hardware, redes y más.

url: ''

github:
  username: alejandroalsa

twitter:
  username: alejandroalsatw

social:
  name: Alejandro Alfaro Sanchez
  email: alejandro@alejandroalsa.es
  links:
    - https://twitter.com/alejandroalsatw
    - https://github.com/alejandroalsa
    - https://www.linkedin.com/in/alejandro-alfaro-sanchez

google_site_verification:

google_analytics:
  id:
  pv:
    proxy_endpoint:
    cache_path:

theme_mode:   # [light|dark]

img_cdn:

avatar: assets/img/alejandroalsa.jpeg

toc: true

comments:
  active:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    input_position:
    lang:
    reactions_enabled:
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
